# Generated by Django 4.2.11 on 2024-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=6)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('revenu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_financement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projet', models.TextField()),
            ],
        ),
    ]
